import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { ControlsTable } from "@/components/assessments/controls-table";
import { PageHero, PageStack } from "@/components/compliance/page-chrome";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Download, ExternalLink } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default async function AssessmentPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}) {
  const { id } = await params;
  const resolvedSearchParams = (searchParams ? await searchParams : {}) ?? {};
  const createdFlag = Array.isArray(resolvedSearchParams.created)
    ? resolvedSearchParams.created[0]
    : resolvedSearchParams.created;

  const assessment = await prisma.assessment.findUnique({
    where: { id },
    include: {
      organization: true,
      engagement: {
        include: {
          customerOrg: true,
          vendorOrg: true,
        },
      },
      findings: {
        include: {
          control: { include: { framework: true } },
        },
      },
    },
  });

  if (!assessment) notFound();

  const rows = assessment.findings.map((f) => ({
    findingId: f.id,
    controlCode: f.control.code,
    controlTitle: f.control.title,
    domain: f.control.domain,
    status: f.status,
    risk: f.risk,
    owner: f.owner,
    notes: f.notes,
    frameworkName: f.control.framework.name,
  }));

  const implementedCount = assessment.findings.filter(
    (f) => f.status === "IMPLEMENTED"
  ).length;
  const totalCount = assessment.findings.length;
  const progressPercent =
    totalCount > 0 ? Math.round((implementedCount / totalCount) * 100) : 0;

  return (
    <PageStack>
      <PageHero
        badge="Assessment detail"
        title={assessment.name}
        description={assessment.organization.name}
        chips={[
          {
            label: `Status: ${assessment.status.replace(/_/g, " ")}`,
            tone:
              assessment.status === "COMPLETE"
                ? "success"
                : assessment.status === "IN_PROGRESS"
                  ? "info"
                  : "neutral",
          },
          { label: `${implementedCount} / ${totalCount} implemented` },
          { label: `${progressPercent}% progress`, tone: progressPercent >= 80 ? "success" : "warning" },
          ...(assessment.engagement?.customerOrg
            ? [{ label: `Customer: ${assessment.engagement.customerOrg.name}`, tone: "info" as const }]
            : []),
        ]}
        actions={
          <Button variant="outline" size="sm" asChild>
            <Link href="/assessments">
              <ArrowLeft className="size-4" />
              Back to Assessments
            </Link>
          </Button>
        }
      />

      {createdFlag === "1" ? (
        <Card className="border-emerald-200 bg-emerald-50/50 shadow-sm">
          <CardHeader className="pb-3">
            <CardTitle className="text-base text-emerald-900">
              Audit Created Successfully
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm text-emerald-950">
            <p>
              This assessment was generated by the New Audit Wizard. Next steps:
            </p>
            <div className="flex flex-wrap gap-2">
              <Button size="sm" asChild>
                <Link href={`/vendor?assessmentId=${assessment.id}`}>
                  Open Vendor Workspace
                  <ExternalLink className="size-4" />
                </Link>
              </Button>
              <Button size="sm" variant="outline" asChild>
                <Link href="/customer">Open Customer Dashboard</Link>
              </Button>
              <Button size="sm" variant="outline" asChild>
                <a href={`/api/reports/assessments/${assessment.id}/csv`}>
                  Export CSV Report
                  <Download className="size-4" />
                </a>
              </Button>
            </div>
            <p className="text-emerald-900/80">
              Workflow: vendor updates control status and evidence, customer reviews submissions and POA&M items, then export a final report.
            </p>
          </CardContent>
        </Card>
      ) : null}

      <div className="flex flex-wrap gap-2">
        <Button size="sm" variant="outline" asChild>
          <Link href={`/vendor?assessmentId=${assessment.id}`}>Vendor Workspace</Link>
        </Button>
        <Button size="sm" variant="outline" asChild>
          <Link href="/customer">Customer Dashboard</Link>
        </Button>
        <Button size="sm" variant="outline" asChild>
          <a href={`/api/reports/assessments/${assessment.id}/csv`}>
            Export CSV Report
            <Download className="size-4" />
          </a>
        </Button>
      </div>

      <ControlsTable rows={rows} assessmentId={assessment.id} />
    </PageStack>
  );
}
